### ISSUE TITLE
Could not start script

### ISSUE THREAD

**Issue by lmgarret** [louismerlin/secretsanta#1]
I tried double clicking on it, and then opening it with Excel as an admin with compatibility mode Windows XP Service Pack 2, did not work. 
Please fix.

**Comment by Cib-e** [comment]
yeah me too :(

**Comment by lmgarret** [comment]
@AndreCI Which version of Excel do you have?

**Comment by louismerlin** [comment]
Added a howto to the README, tell me if you can use it now 🐧

**Comment by lmgarret** [comment]
Perfect, thanks
